### PR TITLE
fix(src/Executables): remove window reload after downloading the lsp

### PR DESCRIPTION
**Pull request by kelwang**
We no longer need to reload the window anymore

### CODE REVIEW

**Comment by kelwang** [comment]
> do we need to get rid of the logging information in the release?

Do you mean the debug log?

**Comment by bthesorceror** [comment]
Yeah

**Comment by kelwang** [comment]
> Yeah

I think it's okay. debug log won't be executed unless people are contributing with the debug mode. production mode won't have that flag

**Comment by kelwang** [comment]
> Yeah

wait, sorry, do you mean the console.log or lsp.log file?

**Pull request merged**
